/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTodoRouteImport } from './routes/_app.todo'
import { Route as AppRepositoryRouteImport } from './routes/_app.repository'
import { Route as AppMastersRouteImport } from './routes/_app.masters'
import { Route as AppConnectRouteImport } from './routes/_app.connect'
import { Route as AppBoRouteImport } from './routes/_app.bo'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppRepositoryIndexRouteImport } from './routes/_app.repository.index'
import { Route as AppMastersIndexRouteImport } from './routes/_app.masters.index'
import { Route as AppConnectIndexRouteImport } from './routes/_app.connect.index'
import { Route as AppBoIndexRouteImport } from './routes/_app.bo.index'
import { Route as AppAnalyticsIndexRouteImport } from './routes/_app.analytics.index'
import { Route as AppAccountIndexRouteImport } from './routes/_app.account.index'
import { Route as AppRepositoryKnowledgeRouteImport } from './routes/_app.repository.knowledge'
import { Route as AppRepositoryClientsRouteImport } from './routes/_app.repository.clients'
import { Route as AppMastersUsersRouteImport } from './routes/_app.masters.users'
import { Route as AppMastersProfilesRouteImport } from './routes/_app.masters.profiles'
import { Route as AppMastersProfileMatrixRouteImport } from './routes/_app.masters.profile-matrix'
import { Route as AppConnectProductMatrixRouteImport } from './routes/_app.connect.product-matrix'
import { Route as AppConnectPlanningRouteImport } from './routes/_app.connect.planning'
import { Route as AppConnectOpportunitiesRouteImport } from './routes/_app.connect.opportunities'
import { Route as AppConnectEngagementsRouteImport } from './routes/_app.connect.engagements'
import { Route as AppBoListingRouteImport } from './routes/_app.bo.listing'
import { Route as AppBoDashboardRouteImport } from './routes/_app.bo.dashboard'
import { Route as AppAnalyticsVelocityRouteImport } from './routes/_app.analytics.velocity'
import { Route as AppAnalyticsEngagementRouteImport } from './routes/_app.analytics.engagement'
import { Route as AppAccountContactsRouteImport } from './routes/_app.account.contacts'
import { Route as AppAccountAccountsRouteImport } from './routes/_app.account.accounts'
import { Route as AppMastersSimpleKeyRouteImport } from './routes/_app.masters.simple.$key'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodoRoute = AppTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoryRoute = AppRepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersRoute = AppMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppBoRoute = AppBoRouteImport.update({
  id: '/bo',
  path: '/bo',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoryIndexRoute = AppRepositoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRepositoryRoute,
} as any)
const AppMastersIndexRoute = AppMastersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMastersRoute,
} as any)
const AppConnectIndexRoute = AppConnectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConnectRoute,
} as any)
const AppBoIndexRoute = AppBoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBoRoute,
} as any)
const AppAnalyticsIndexRoute = AppAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAnalyticsRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppRepositoryKnowledgeRoute = AppRepositoryKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRepositoryRoute,
} as any)
const AppRepositoryClientsRoute = AppRepositoryClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRepositoryRoute,
} as any)
const AppMastersUsersRoute = AppMastersUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppMastersRoute,
} as any)
const AppMastersProfilesRoute = AppMastersProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AppMastersRoute,
} as any)
const AppMastersProfileMatrixRoute = AppMastersProfileMatrixRouteImport.update({
  id: '/profile-matrix',
  path: '/profile-matrix',
  getParentRoute: () => AppMastersRoute,
} as any)
const AppConnectProductMatrixRoute = AppConnectProductMatrixRouteImport.update({
  id: '/product-matrix',
  path: '/product-matrix',
  getParentRoute: () => AppConnectRoute,
} as any)
const AppConnectPlanningRoute = AppConnectPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AppConnectRoute,
} as any)
const AppConnectOpportunitiesRoute = AppConnectOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppConnectRoute,
} as any)
const AppConnectEngagementsRoute = AppConnectEngagementsRouteImport.update({
  id: '/engagements',
  path: '/engagements',
  getParentRoute: () => AppConnectRoute,
} as any)
const AppBoListingRoute = AppBoListingRouteImport.update({
  id: '/listing',
  path: '/listing',
  getParentRoute: () => AppBoRoute,
} as any)
const AppBoDashboardRoute = AppBoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppBoRoute,
} as any)
const AppAnalyticsVelocityRoute = AppAnalyticsVelocityRouteImport.update({
  id: '/velocity',
  path: '/velocity',
  getParentRoute: () => AppAnalyticsRoute,
} as any)
const AppAnalyticsEngagementRoute = AppAnalyticsEngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => AppAnalyticsRoute,
} as any)
const AppAccountContactsRoute = AppAccountContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountAccountsRoute = AppAccountAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppMastersSimpleKeyRoute = AppMastersSimpleKeyRouteImport.update({
  id: '/simple/$key',
  path: '/simple/$key',
  getParentRoute: () => AppMastersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AppAccountRouteWithChildren
  '/analytics': typeof AppAnalyticsRouteWithChildren
  '/bo': typeof AppBoRouteWithChildren
  '/connect': typeof AppConnectRouteWithChildren
  '/masters': typeof AppMastersRouteWithChildren
  '/repository': typeof AppRepositoryRouteWithChildren
  '/todo': typeof AppTodoRoute
  '/account/accounts': typeof AppAccountAccountsRoute
  '/account/contacts': typeof AppAccountContactsRoute
  '/analytics/engagement': typeof AppAnalyticsEngagementRoute
  '/analytics/velocity': typeof AppAnalyticsVelocityRoute
  '/bo/dashboard': typeof AppBoDashboardRoute
  '/bo/listing': typeof AppBoListingRoute
  '/connect/engagements': typeof AppConnectEngagementsRoute
  '/connect/opportunities': typeof AppConnectOpportunitiesRoute
  '/connect/planning': typeof AppConnectPlanningRoute
  '/connect/product-matrix': typeof AppConnectProductMatrixRoute
  '/masters/profile-matrix': typeof AppMastersProfileMatrixRoute
  '/masters/profiles': typeof AppMastersProfilesRoute
  '/masters/users': typeof AppMastersUsersRoute
  '/repository/clients': typeof AppRepositoryClientsRoute
  '/repository/knowledge': typeof AppRepositoryKnowledgeRoute
  '/account/': typeof AppAccountIndexRoute
  '/analytics/': typeof AppAnalyticsIndexRoute
  '/bo/': typeof AppBoIndexRoute
  '/connect/': typeof AppConnectIndexRoute
  '/masters/': typeof AppMastersIndexRoute
  '/repository/': typeof AppRepositoryIndexRoute
  '/masters/simple/$key': typeof AppMastersSimpleKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todo': typeof AppTodoRoute
  '/account/accounts': typeof AppAccountAccountsRoute
  '/account/contacts': typeof AppAccountContactsRoute
  '/analytics/engagement': typeof AppAnalyticsEngagementRoute
  '/analytics/velocity': typeof AppAnalyticsVelocityRoute
  '/bo/dashboard': typeof AppBoDashboardRoute
  '/bo/listing': typeof AppBoListingRoute
  '/connect/engagements': typeof AppConnectEngagementsRoute
  '/connect/opportunities': typeof AppConnectOpportunitiesRoute
  '/connect/planning': typeof AppConnectPlanningRoute
  '/connect/product-matrix': typeof AppConnectProductMatrixRoute
  '/masters/profile-matrix': typeof AppMastersProfileMatrixRoute
  '/masters/profiles': typeof AppMastersProfilesRoute
  '/masters/users': typeof AppMastersUsersRoute
  '/repository/clients': typeof AppRepositoryClientsRoute
  '/repository/knowledge': typeof AppRepositoryKnowledgeRoute
  '/account': typeof AppAccountIndexRoute
  '/analytics': typeof AppAnalyticsIndexRoute
  '/bo': typeof AppBoIndexRoute
  '/connect': typeof AppConnectIndexRoute
  '/masters': typeof AppMastersIndexRoute
  '/repository': typeof AppRepositoryIndexRoute
  '/masters/simple/$key': typeof AppMastersSimpleKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRouteWithChildren
  '/_app/bo': typeof AppBoRouteWithChildren
  '/_app/connect': typeof AppConnectRouteWithChildren
  '/_app/masters': typeof AppMastersRouteWithChildren
  '/_app/repository': typeof AppRepositoryRouteWithChildren
  '/_app/todo': typeof AppTodoRoute
  '/_app/account/accounts': typeof AppAccountAccountsRoute
  '/_app/account/contacts': typeof AppAccountContactsRoute
  '/_app/analytics/engagement': typeof AppAnalyticsEngagementRoute
  '/_app/analytics/velocity': typeof AppAnalyticsVelocityRoute
  '/_app/bo/dashboard': typeof AppBoDashboardRoute
  '/_app/bo/listing': typeof AppBoListingRoute
  '/_app/connect/engagements': typeof AppConnectEngagementsRoute
  '/_app/connect/opportunities': typeof AppConnectOpportunitiesRoute
  '/_app/connect/planning': typeof AppConnectPlanningRoute
  '/_app/connect/product-matrix': typeof AppConnectProductMatrixRoute
  '/_app/masters/profile-matrix': typeof AppMastersProfileMatrixRoute
  '/_app/masters/profiles': typeof AppMastersProfilesRoute
  '/_app/masters/users': typeof AppMastersUsersRoute
  '/_app/repository/clients': typeof AppRepositoryClientsRoute
  '/_app/repository/knowledge': typeof AppRepositoryKnowledgeRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/analytics/': typeof AppAnalyticsIndexRoute
  '/_app/bo/': typeof AppBoIndexRoute
  '/_app/connect/': typeof AppConnectIndexRoute
  '/_app/masters/': typeof AppMastersIndexRoute
  '/_app/repository/': typeof AppRepositoryIndexRoute
  '/_app/masters/simple/$key': typeof AppMastersSimpleKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/analytics'
    | '/bo'
    | '/connect'
    | '/masters'
    | '/repository'
    | '/todo'
    | '/account/accounts'
    | '/account/contacts'
    | '/analytics/engagement'
    | '/analytics/velocity'
    | '/bo/dashboard'
    | '/bo/listing'
    | '/connect/engagements'
    | '/connect/opportunities'
    | '/connect/planning'
    | '/connect/product-matrix'
    | '/masters/profile-matrix'
    | '/masters/profiles'
    | '/masters/users'
    | '/repository/clients'
    | '/repository/knowledge'
    | '/account/'
    | '/analytics/'
    | '/bo/'
    | '/connect/'
    | '/masters/'
    | '/repository/'
    | '/masters/simple/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/todo'
    | '/account/accounts'
    | '/account/contacts'
    | '/analytics/engagement'
    | '/analytics/velocity'
    | '/bo/dashboard'
    | '/bo/listing'
    | '/connect/engagements'
    | '/connect/opportunities'
    | '/connect/planning'
    | '/connect/product-matrix'
    | '/masters/profile-matrix'
    | '/masters/profiles'
    | '/masters/users'
    | '/repository/clients'
    | '/repository/knowledge'
    | '/account'
    | '/analytics'
    | '/bo'
    | '/connect'
    | '/masters'
    | '/repository'
    | '/masters/simple/$key'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/account'
    | '/_app/analytics'
    | '/_app/bo'
    | '/_app/connect'
    | '/_app/masters'
    | '/_app/repository'
    | '/_app/todo'
    | '/_app/account/accounts'
    | '/_app/account/contacts'
    | '/_app/analytics/engagement'
    | '/_app/analytics/velocity'
    | '/_app/bo/dashboard'
    | '/_app/bo/listing'
    | '/_app/connect/engagements'
    | '/_app/connect/opportunities'
    | '/_app/connect/planning'
    | '/_app/connect/product-matrix'
    | '/_app/masters/profile-matrix'
    | '/_app/masters/profiles'
    | '/_app/masters/users'
    | '/_app/repository/clients'
    | '/_app/repository/knowledge'
    | '/_app/account/'
    | '/_app/analytics/'
    | '/_app/bo/'
    | '/_app/connect/'
    | '/_app/masters/'
    | '/_app/repository/'
    | '/_app/masters/simple/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/todo': {
      id: '/_app/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof AppTodoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repository': {
      id: '/_app/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof AppRepositoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters': {
      id: '/_app/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AppMastersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bo': {
      id: '/_app/bo'
      path: '/bo'
      fullPath: '/bo'
      preLoaderRoute: typeof AppBoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repository/': {
      id: '/_app/repository/'
      path: '/'
      fullPath: '/repository/'
      preLoaderRoute: typeof AppRepositoryIndexRouteImport
      parentRoute: typeof AppRepositoryRoute
    }
    '/_app/masters/': {
      id: '/_app/masters/'
      path: '/'
      fullPath: '/masters/'
      preLoaderRoute: typeof AppMastersIndexRouteImport
      parentRoute: typeof AppMastersRoute
    }
    '/_app/connect/': {
      id: '/_app/connect/'
      path: '/'
      fullPath: '/connect/'
      preLoaderRoute: typeof AppConnectIndexRouteImport
      parentRoute: typeof AppConnectRoute
    }
    '/_app/bo/': {
      id: '/_app/bo/'
      path: '/'
      fullPath: '/bo/'
      preLoaderRoute: typeof AppBoIndexRouteImport
      parentRoute: typeof AppBoRoute
    }
    '/_app/analytics/': {
      id: '/_app/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AppAnalyticsIndexRouteImport
      parentRoute: typeof AppAnalyticsRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/repository/knowledge': {
      id: '/_app/repository/knowledge'
      path: '/knowledge'
      fullPath: '/repository/knowledge'
      preLoaderRoute: typeof AppRepositoryKnowledgeRouteImport
      parentRoute: typeof AppRepositoryRoute
    }
    '/_app/repository/clients': {
      id: '/_app/repository/clients'
      path: '/clients'
      fullPath: '/repository/clients'
      preLoaderRoute: typeof AppRepositoryClientsRouteImport
      parentRoute: typeof AppRepositoryRoute
    }
    '/_app/masters/users': {
      id: '/_app/masters/users'
      path: '/users'
      fullPath: '/masters/users'
      preLoaderRoute: typeof AppMastersUsersRouteImport
      parentRoute: typeof AppMastersRoute
    }
    '/_app/masters/profiles': {
      id: '/_app/masters/profiles'
      path: '/profiles'
      fullPath: '/masters/profiles'
      preLoaderRoute: typeof AppMastersProfilesRouteImport
      parentRoute: typeof AppMastersRoute
    }
    '/_app/masters/profile-matrix': {
      id: '/_app/masters/profile-matrix'
      path: '/profile-matrix'
      fullPath: '/masters/profile-matrix'
      preLoaderRoute: typeof AppMastersProfileMatrixRouteImport
      parentRoute: typeof AppMastersRoute
    }
    '/_app/connect/product-matrix': {
      id: '/_app/connect/product-matrix'
      path: '/product-matrix'
      fullPath: '/connect/product-matrix'
      preLoaderRoute: typeof AppConnectProductMatrixRouteImport
      parentRoute: typeof AppConnectRoute
    }
    '/_app/connect/planning': {
      id: '/_app/connect/planning'
      path: '/planning'
      fullPath: '/connect/planning'
      preLoaderRoute: typeof AppConnectPlanningRouteImport
      parentRoute: typeof AppConnectRoute
    }
    '/_app/connect/opportunities': {
      id: '/_app/connect/opportunities'
      path: '/opportunities'
      fullPath: '/connect/opportunities'
      preLoaderRoute: typeof AppConnectOpportunitiesRouteImport
      parentRoute: typeof AppConnectRoute
    }
    '/_app/connect/engagements': {
      id: '/_app/connect/engagements'
      path: '/engagements'
      fullPath: '/connect/engagements'
      preLoaderRoute: typeof AppConnectEngagementsRouteImport
      parentRoute: typeof AppConnectRoute
    }
    '/_app/bo/listing': {
      id: '/_app/bo/listing'
      path: '/listing'
      fullPath: '/bo/listing'
      preLoaderRoute: typeof AppBoListingRouteImport
      parentRoute: typeof AppBoRoute
    }
    '/_app/bo/dashboard': {
      id: '/_app/bo/dashboard'
      path: '/dashboard'
      fullPath: '/bo/dashboard'
      preLoaderRoute: typeof AppBoDashboardRouteImport
      parentRoute: typeof AppBoRoute
    }
    '/_app/analytics/velocity': {
      id: '/_app/analytics/velocity'
      path: '/velocity'
      fullPath: '/analytics/velocity'
      preLoaderRoute: typeof AppAnalyticsVelocityRouteImport
      parentRoute: typeof AppAnalyticsRoute
    }
    '/_app/analytics/engagement': {
      id: '/_app/analytics/engagement'
      path: '/engagement'
      fullPath: '/analytics/engagement'
      preLoaderRoute: typeof AppAnalyticsEngagementRouteImport
      parentRoute: typeof AppAnalyticsRoute
    }
    '/_app/account/contacts': {
      id: '/_app/account/contacts'
      path: '/contacts'
      fullPath: '/account/contacts'
      preLoaderRoute: typeof AppAccountContactsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/accounts': {
      id: '/_app/account/accounts'
      path: '/accounts'
      fullPath: '/account/accounts'
      preLoaderRoute: typeof AppAccountAccountsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/masters/simple/$key': {
      id: '/_app/masters/simple/$key'
      path: '/simple/$key'
      fullPath: '/masters/simple/$key'
      preLoaderRoute: typeof AppMastersSimpleKeyRouteImport
      parentRoute: typeof AppMastersRoute
    }
  }
}

interface AppAccountRouteChildren {
  AppAccountAccountsRoute: typeof AppAccountAccountsRoute
  AppAccountContactsRoute: typeof AppAccountContactsRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountAccountsRoute: AppAccountAccountsRoute,
  AppAccountContactsRoute: AppAccountContactsRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppAnalyticsRouteChildren {
  AppAnalyticsEngagementRoute: typeof AppAnalyticsEngagementRoute
  AppAnalyticsVelocityRoute: typeof AppAnalyticsVelocityRoute
  AppAnalyticsIndexRoute: typeof AppAnalyticsIndexRoute
}

const AppAnalyticsRouteChildren: AppAnalyticsRouteChildren = {
  AppAnalyticsEngagementRoute: AppAnalyticsEngagementRoute,
  AppAnalyticsVelocityRoute: AppAnalyticsVelocityRoute,
  AppAnalyticsIndexRoute: AppAnalyticsIndexRoute,
}

const AppAnalyticsRouteWithChildren = AppAnalyticsRoute._addFileChildren(
  AppAnalyticsRouteChildren,
)

interface AppBoRouteChildren {
  AppBoDashboardRoute: typeof AppBoDashboardRoute
  AppBoListingRoute: typeof AppBoListingRoute
  AppBoIndexRoute: typeof AppBoIndexRoute
}

const AppBoRouteChildren: AppBoRouteChildren = {
  AppBoDashboardRoute: AppBoDashboardRoute,
  AppBoListingRoute: AppBoListingRoute,
  AppBoIndexRoute: AppBoIndexRoute,
}

const AppBoRouteWithChildren = AppBoRoute._addFileChildren(AppBoRouteChildren)

interface AppConnectRouteChildren {
  AppConnectEngagementsRoute: typeof AppConnectEngagementsRoute
  AppConnectOpportunitiesRoute: typeof AppConnectOpportunitiesRoute
  AppConnectPlanningRoute: typeof AppConnectPlanningRoute
  AppConnectProductMatrixRoute: typeof AppConnectProductMatrixRoute
  AppConnectIndexRoute: typeof AppConnectIndexRoute
}

const AppConnectRouteChildren: AppConnectRouteChildren = {
  AppConnectEngagementsRoute: AppConnectEngagementsRoute,
  AppConnectOpportunitiesRoute: AppConnectOpportunitiesRoute,
  AppConnectPlanningRoute: AppConnectPlanningRoute,
  AppConnectProductMatrixRoute: AppConnectProductMatrixRoute,
  AppConnectIndexRoute: AppConnectIndexRoute,
}

const AppConnectRouteWithChildren = AppConnectRoute._addFileChildren(
  AppConnectRouteChildren,
)

interface AppMastersRouteChildren {
  AppMastersProfileMatrixRoute: typeof AppMastersProfileMatrixRoute
  AppMastersProfilesRoute: typeof AppMastersProfilesRoute
  AppMastersUsersRoute: typeof AppMastersUsersRoute
  AppMastersIndexRoute: typeof AppMastersIndexRoute
  AppMastersSimpleKeyRoute: typeof AppMastersSimpleKeyRoute
}

const AppMastersRouteChildren: AppMastersRouteChildren = {
  AppMastersProfileMatrixRoute: AppMastersProfileMatrixRoute,
  AppMastersProfilesRoute: AppMastersProfilesRoute,
  AppMastersUsersRoute: AppMastersUsersRoute,
  AppMastersIndexRoute: AppMastersIndexRoute,
  AppMastersSimpleKeyRoute: AppMastersSimpleKeyRoute,
}

const AppMastersRouteWithChildren = AppMastersRoute._addFileChildren(
  AppMastersRouteChildren,
)

interface AppRepositoryRouteChildren {
  AppRepositoryClientsRoute: typeof AppRepositoryClientsRoute
  AppRepositoryKnowledgeRoute: typeof AppRepositoryKnowledgeRoute
  AppRepositoryIndexRoute: typeof AppRepositoryIndexRoute
}

const AppRepositoryRouteChildren: AppRepositoryRouteChildren = {
  AppRepositoryClientsRoute: AppRepositoryClientsRoute,
  AppRepositoryKnowledgeRoute: AppRepositoryKnowledgeRoute,
  AppRepositoryIndexRoute: AppRepositoryIndexRoute,
}

const AppRepositoryRouteWithChildren = AppRepositoryRoute._addFileChildren(
  AppRepositoryRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRouteWithChildren
  AppBoRoute: typeof AppBoRouteWithChildren
  AppConnectRoute: typeof AppConnectRouteWithChildren
  AppMastersRoute: typeof AppMastersRouteWithChildren
  AppRepositoryRoute: typeof AppRepositoryRouteWithChildren
  AppTodoRoute: typeof AppTodoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRouteWithChildren,
  AppBoRoute: AppBoRouteWithChildren,
  AppConnectRoute: AppConnectRouteWithChildren,
  AppMastersRoute: AppMastersRouteWithChildren,
  AppRepositoryRoute: AppRepositoryRouteWithChildren,
  AppTodoRoute: AppTodoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
